# Generated by Django 2.2.4 on 2020-12-20 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_article_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articlelikeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUnlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_Unlike', to='articleapp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_Unlike', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
    ]
