# Generated by Django 2.2.4 on 2020-12-18 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aricle',
            new_name='Article',
        ),
    ]
