# Generated by Django 2.2.4 on 2020-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
